[package]
name = "qubit-ge"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30.10", features = ["android-native-activity"] }
env_logger = "0.11.8"
log = "0.4"
wgpu = "25.0"
pollster = "0.4.0"