name: .NET Build on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Adjust this version based on your project

    - name: Restore dependencies
      run: dotnet restore

    - name: Build library (Qubit.Engine)
      run: dotnet build Qubit.Engine/Qubit.Engine.csproj --configuration Release --no-restore

    - name: Build executable (PointLonely)
      run: dotnet build PointLonely/PointLonely.csproj --configuration Release --no-restore

    - name: Publish library (Qubit.Engine)
      run: dotnet publish Qubit.Engine/Qubit.Engine.csproj --configuration Release --output ./artifacts/Qubit.Engine

    - name: Publish executable (PointLonely)
      run: dotnet publish PointLonely/PointLonely.csproj --configuration Release --output ./artifacts/PointLonely

    - name: Upload library artifact
      uses: actions/upload-artifact@v4
      with:
        name: Qubit.Engine-library
        path: ./artifacts/Qubit.Engine

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: PointLonely-executable
        path: ./artifacts/PointLonely
